### ISSUE TITLE
Redirect to HTTPS

### ISSUE THREAD

**Issue by Madis0** [charmander/safeguard#2]
_Since there is a growing need of HTTPS redirector addons, I thought I should clarify [my negative review](https://addons.mozilla.org/en-US/firefox/addon/safeguard/reviews/908204/) more to support this project._

What I meant by _HTTPS redirect_ is similar behaviour to [Smart HTTPS](https://addons.mozilla.org/en-US/firefox/addon/smart-https-revived/)/[HTTPS by default](https://addons.mozilla.org/en-US/firefox/addon/https-by-default/)/[HTTPS Already](https://addons.mozilla.org/en-US/firefox/addon/https-already/) - block initial http request with a [blocking onWebRequest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeRequest), load it as https and if it fails, show an error page (like the one you have now).

What do you think about that? That wouldn't compromise the security like a server-sided redirect would, because the browser blocks the insecure request before it is made.

**Comment by charmander** [comment]
I personally prefer to choose explicitly, but will consider adding an option.

**Comment by charmander** [comment]
Deciding to keep this explicit with the redirect page.
